alter table public.store_settings enable row level security; alter table public.store_categories enable row level security; alter table public.store_products enable row level security; alter table public.product_variants enable row level security; alter table public.customers enable row level security; alter table public.customer_addresses enable row level security; alter table public.customer_activities enable row level security; alter table public.carts enable row level security; alter table public.cart_items enable row level security; alter table public.orders enable row level security; alter table public.order_items enable row level security; alter table public.payments enable row level security; alter table public.shipments enable row level security; alter table public.returns enable row level security; alter table public.refunds enable row level security; alter table public.coupons enable row level security; alter table public.opportunities enable row level security; alter table public.commerce_tasks enable row level security; alter table public.campaigns enable row level security; alter table public.reviews enable row level security; alter table public.audit_logs enable row level security;
create or replace function public.is_admin() returns boolean language sql stable security definer set search_path=public as $$ select exists(select 1 from public.profiles where id=auth.uid() and role='admin') $$;
create policy "public read active categories" on public.store_categories for select using(active=true);
create policy "public read active products" on public.store_products for select using(active=true);
create policy "public read active variants" on public.product_variants for select using(active=true);
create policy "admin categories" on public.store_categories for all using(public.is_admin()) with check(public.is_admin());
create policy "admin products" on public.store_products for all using(public.is_admin()) with check(public.is_admin());
create policy "admin variants" on public.product_variants for all using(public.is_admin()) with check(public.is_admin());
create policy "customer reads self" on public.customers for select using(auth.uid()=auth_user_id or public.is_admin());
create policy "customer updates self" on public.customers for update using(auth.uid()=auth_user_id or public.is_admin());
create policy "customer reads own orders" on public.orders for select using(public.is_admin() or customer_id in(select id from public.customers where auth_user_id=auth.uid()));
create policy "admin orders" on public.orders for all using(public.is_admin()) with check(public.is_admin());
create policy "customer reads own order items" on public.order_items for select using(public.is_admin() or order_id in(select o.id from public.orders o join public.customers c on c.id=o.customer_id where c.auth_user_id=auth.uid()));
create policy "admin order items" on public.order_items for all using(public.is_admin()) with check(public.is_admin());
create policy "admin payments" on public.payments for all using(public.is_admin()) with check(public.is_admin());
create policy "admin shipments" on public.shipments for all using(public.is_admin()) with check(public.is_admin());
create policy "admin returns" on public.returns for all using(public.is_admin()) with check(public.is_admin());
create policy "admin refunds" on public.refunds for all using(public.is_admin()) with check(public.is_admin());
create policy "admin crm" on public.customer_activities for all using(public.is_admin()) with check(public.is_admin());
create policy "admin opportunities" on public.opportunities for all using(public.is_admin()) with check(public.is_admin());
create policy "admin tasks" on public.commerce_tasks for all using(public.is_admin()) with check(public.is_admin());
create policy "admin campaigns" on public.campaigns for all using(public.is_admin()) with check(public.is_admin());
create policy "public approved reviews" on public.reviews for select using(status='approved' or public.is_admin());
create policy "admin reviews" on public.reviews for all using(public.is_admin()) with check(public.is_admin());
create policy "admin audit" on public.audit_logs for select using(public.is_admin());
