(function(){'use strict';
const locale=document.documentElement.lang==='ar'?'ar':'en',KEY='asolution_cart_v2',id=new URLSearchParams(location.search).get('id'),root=document.querySelector('#product-root'),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));let product=null,variants=[],settings={currency:'SAR'};
const visuals={'web-launch':['photo-1460925895917-afdab827c52f','photo-1516321318423-f06f85e504b3','photo-1497366811353-6870744d04b2'],commerce:['photo-1556742049-0cfed4f6a45d','photo-1556742111-a301076d9d18','photo-1556742502-ec7c0e9f34b1'],'brand-system':['photo-1558655146-9f40138edfeb','photo-1561070791-2526d30994b5','photo-1542744173-8e7e53415bb0'],growth:['photo-1551288049-bebda4e38f71','photo-1460925895917-afdab827c52f','photo-1498050108023-c5249f4df085'],crm:['photo-1497366754035-f200968a6e72','photo-1497215728101-856f4ea42174','photo-1497366811353-6870744d04b2'],social:['photo-1611162617474-5b21e879e113','photo-1611162616305-c69b3fa7fbe0','photo-1492724441997-5dc865305da7']};
const img=(pid,i=0)=>`https://images.unsplash.com/${(visuals[pid]||visuals['web-launch'])[i]}?auto=format&fit=crop&w=${i?1000:1700}&q=88`;
const c=locale==='ar'?{bad:'الحل غير موجود',from:'ابتداءً من',add:'أضف للسلة',includes:'ماذا ستحصل عليه',reviews:'آراء العملاء',back:'العودة للمتجر',variant:'الخيار',outcome:'النتيجة / معاينة بصرية',stock:'متوفر',out:'غير متوفر',unavailable:'لا توجد خيارات متاحة حالياً',steps:[['نحدد الهدف','نحدد هدف العمل والنطاق والمدخلات.'],['نصنع الحل','الاستراتيجية والتصميم والتنفيذ تتحرك كمنظومة واحدة.'],['نسلّم','تحصل على حل أعمال مصقول وجاهز للإطلاق.']]}:{bad:'Solution not found',from:'FROM',add:'ADD TO CART',includes:"WHAT YOU’LL GET",reviews:'CLIENT REVIEWS',back:'BACK TO STORE',variant:'OPTION',outcome:'THE OUTCOME / VISUAL PREVIEW',stock:'in stock',out:'out of stock',unavailable:'No options are currently available',steps:[['ALIGN','We lock the business objective, scope and inputs.'],['CREATE','Strategy, design and implementation move as one.'],['DELIVER','You receive a polished, launch-ready business solution.']]};
function read(){try{const v=JSON.parse(localStorage.getItem(KEY)||'[]');return Array.isArray(v)?v:[]}catch{return[]}}function save(v){try{localStorage.setItem(KEY,JSON.stringify(v))}catch{}}
const money=v=>new Intl.NumberFormat(locale==='ar'?'ar-SA':'en-SA',{style:'currency',currency:settings.currency||'SAR'}).format(Number(v)||0);
function selectedVariant(){const vid=document.querySelector('#variant-select')?.value;return variants.find(v=>String(v.id)===String(vid))}
function add(){const v=selectedVariant();if(product?.type==='physical'&&(!v||Number(v.inventory_qty||0)<=0))return;const variantId=v?.id?String(v.id):null,cart=read(),item=cart.find(x=>x.id===id&&(x.variantId||null)===(variantId||null));if(item)item.qty=Math.min(99,Number(item.qty||0)+1);else cart.push({id,qty:1,variantId});save(cart);location.href='index.html'}
function setMeta(t){document.title=`${t.name} — A Solution Store`;let m=document.querySelector('meta[name=description]');if(!m){m=document.createElement('meta');m.name='description';document.head.appendChild(m)}m.content=(t.desc||'').slice(0,160)}
function render(){if(!root)return;if(!product){root.innerHTML=`<section class="product-copy"><h1>${c.bad}</h1><a class="primary" href="index.html">${c.back} ↗</a></section>`;return}const t=product[locale],available=variants.filter(v=>Number(v.inventory_qty??1)>0),physical=product.type==='physical',variantMarkup=physical?(available.length?`<label class="field product-variant"><span>${c.variant}</span><select id="variant-select">${available.map(v=>`<option value="${esc(v.id)}">${esc(locale==='ar'?(v.name_ar||v.name_en):(v.name_en||v.name_ar))} — ${money(v.price??product.price)} · ${Number(v.inventory_qty)} ${c.stock}</option>`).join('')}</select></label>`:`<p class="empty-state">${c.unavailable}</p>`):'';const initial=available[0]?.price??product.price;root.classList.add('product-experience');root.innerHTML=`<section class="product-visual-hero"><div class="product-art premium-product-art"><img class="product-art-img" src="${img(product.id)}" alt="${esc(t.name)}"></div><div class="product-copy premium-product-copy"><small>${esc(t.eyebrow||'A SOLUTION')}</small><h1>${esc(t.name)}</h1><p class="product-lead">${esc(t.desc||'')}</p>${variantMarkup}<div class="price product-price">${c.from} <span id="live-price">${money(initial)}</span></div><button class="primary product-add" id="product-add" ${physical&&!available.length?'disabled':''}>${physical&&!available.length?c.out:c.add} +</button></div></section><section class="product-story"><span class="section-no">${c.outcome}</span><div class="product-gallery"><img src="${img(product.id,0)}" alt=""><img src="${img(product.id,1)}" alt=""><img src="${img(product.id,2)}" alt=""></div><div class="product-deliverables"><h2>${c.includes}</h2><ul>${(t.bullets||[]).map(x=>`<li>${esc(x)}</li>`).join('')}</ul></div><div class="delivery-steps">${c.steps.map((x,i)=>`<article><b>0${i+1}</b><h4>${x[0]}</h4><p>${x[1]}</p></article>`).join('')}</div><div id="product-reviews" class="reviews-block"><h3>${c.reviews}</h3></div></section>`;document.querySelector('#product-add').onclick=add;document.querySelector('#variant-select')?.addEventListener('change',()=>{const v=selectedVariant();document.querySelector('#live-price').textContent=money(v?.price??product.price)});setMeta(t);loadReviews()}
async function loadReviews(){const box=document.querySelector('#product-reviews');try{const reviews=await ASolutionRemote.listReviews(product.remoteId);box.innerHTML+=reviews?.length?reviews.map(r=>`<article class="review"><b>${'★'.repeat(r.rating)}${'☆'.repeat(5-r.rating)}</b><h4>${esc(r.title||'')}</h4><p>${esc(r.body||'')}</p></article>`).join(''):`<p>${locale==='ar'?'لا توجد تقييمات منشورة بعد.':'No published reviews yet.'}</p>`}catch{}}
(async()=>{try{const [rows,s]=await Promise.all([ASolutionRemote.listProducts(),ASolutionRemote.listSettings()]);settings=s||settings;const r=rows.find(x=>x.slug===id);if(!r){render();return}product={id:r.slug,remoteId:r.id,type:r.type,price:Number(r.price),en:{name:r.name_en,eyebrow:r.eyebrow_en||'A SOLUTION',desc:r.description_en||'',bullets:Array.isArray(r.features_en)?r.features_en:[]},ar:{name:r.name_ar||r.name_en,eyebrow:r.eyebrow_ar||r.eyebrow_en||'A SOLUTION',desc:r.description_ar||r.description_en||'',bullets:Array.isArray(r.features_ar)?r.features_ar:[]}};if(r.type==='physical')variants=await ASolutionRemote.listVariants(r.id);render()}catch{render()}})();
})();