(function(){
'use strict';
const core=window.ASolutionStore||{},$=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
const locale=document.documentElement.lang==='ar'?'ar':'en',KEY='asolution_cart_v2',WKEY='asolution_wishlist_local';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const visuals={'web-launch':'photo-1460925895917-afdab827c52f',commerce:'photo-1556742049-0cfed4f6a45d','brand-system':'photo-1558655146-9f40138edfeb',growth:'photo-1551288049-bebda4e38f71',crm:'photo-1497366754035-f200968a6e72',social:'photo-1611162617474-5b21e879e113'};
const visualForProduct=id=>`https://images.unsplash.com/${visuals[id]||visuals['web-launch']}?auto=format&fit=crop&w=1400&q=88`;
function readArray(k){try{const v=JSON.parse(localStorage.getItem(k)||'[]');return Array.isArray(v)?v:[]}catch{return[]}}
function saveArray(k,v){try{localStorage.setItem(k,JSON.stringify(v))}catch{}}
let rawCart=readArray(KEY).filter(x=>x&&x.id&&Number(x.qty)>0).map(x=>({id:String(x.id),qty:Math.min(99,Math.max(1,Math.floor(Number(x.qty)||1))),variantId:x.variantId?String(x.variantId):null}));
let cart=[...rawCart],wishlist=readArray(WKEY).filter(x=>typeof x==='string'),catalog=(core.PRODUCTS||[]).map(p=>({...p,remoteId:null})),variants=[],categories=[],activeCategory='all',query='',settings={currency:'SAR',vat_rate:.15};
const copy=locale==='ar'?{add:'أضف للسلة',from:'ابتداءً من',empty:'السلة فارغة.',checkout:'إتمام الطلب',subtotal:'المجموع',vat:'الضريبة',total:'الإجمالي',view:'شاهد التجربة',wish:'المفضلة',search:'ابحث عن حل...',all:'كل الحلول'}:{add:'ADD TO CART',from:'FROM',empty:'Your cart is empty.',checkout:'CHECKOUT',subtotal:'Subtotal',vat:'VAT',total:'Total',view:'SEE THE EXPERIENCE',wish:'WISHLIST',search:'Search solutions...',all:'All Solutions'};
const translated=p=>p?.[locale]||p?.en||{name:'A Solution',eyebrow:'A SOLUTION',desc:''};
const money=v=>new Intl.NumberFormat(locale==='ar'?'ar-SA':'en-SA',{style:'currency',currency:settings.currency||'SAR',maximumFractionDigits:2}).format(Number(v)||0);
const product=id=>catalog.find(p=>p.id===id),variant=id=>variants.find(v=>String(v.id)===String(id));
const unitPrice=x=>Number(variant(x.variantId)?.price??product(x.id)?.price??0);
function normalize(){const ids=new Set(catalog.map(p=>p.id));cart=rawCart.filter(x=>ids.has(x.id));saveArray(KEY,cart)}
function add(id,variantId=null){if(!product(id))return;const key=variantId?String(variantId):null,item=cart.find(x=>x.id===id&&x.variantId===key);if(item)item.qty=Math.min(99,item.qty+1);else cart.push({id,qty:1,variantId:key});rawCart=[...cart];saveArray(KEY,cart);renderCart();openCart()}
function setQty(id,variantId,qty){const key=variantId?String(variantId):null;if(qty<=0)cart=cart.filter(x=>!(x.id===id&&x.variantId===key));else cart=cart.map(x=>x.id===id&&x.variantId===key?{...x,qty:Math.min(99,Math.max(1,qty))}:x);rawCart=[...cart];saveArray(KEY,cart);renderCart()}
function card(p,featured=false){const t=translated(p),liked=wishlist.includes(p.id),cls=featured?'featured':'catalog';return `<article class="${cls}-card"><a class="${cls}-art" href="product.html?id=${encodeURIComponent(p.id)}"><img src="${visualForProduct(p.id)}" alt="${esc(t.name)} — real-world visual" loading="lazy"></a><div class="${cls}-body ${featured?'featured-copy':''}"><small>${esc(t.eyebrow||'A SOLUTION')}</small><h3>${esc(t.name)}</h3><p>${esc(t.desc||'')}</p><div class="${featured?'featured-price':'price'}">${copy.from} ${money(p.price)}</div><div class="${cls}-actions"><a href="product.html?id=${encodeURIComponent(p.id)}">${copy.view} ↗</a><button data-add="${esc(p.id)}">${featured?'+':copy.add}</button><button class="wish-inline" data-wishlist="${esc(p.id)}" aria-label="${copy.wish}">${liked?'♥':'♡'}</button></div></div></article>`}
function visible(){const q=query.toLowerCase().trim();return catalog.filter(p=>(activeCategory==='all'||p.category===activeCategory)&&(!q||`${p.en?.name||''} ${p.ar?.name||''} ${p.en?.desc||''} ${p.ar?.desc||''}`.toLowerCase().includes(q)))}
function bindCards(){$$('[data-add]').forEach(b=>b.onclick=()=>add(b.dataset.add));$$('[data-wishlist]').forEach(b=>b.onclick=async()=>{const id=b.dataset.wishlist;wishlist=wishlist.includes(id)?wishlist.filter(x=>x!==id):[...wishlist,id];saveArray(WKEY,wishlist);renderCatalog();renderFeatured();$$('.wishlist-count').forEach(x=>x.textContent=wishlist.length);try{const p=product(id),token=ASolutionRemote.session()?.access_token;if(p?.remoteId&&token){if(wishlist.includes(id))await ASolutionRemote.addWishlist(p.remoteId);else await ASolutionRemote.removeWishlist(p.remoteId)}}catch{}})}
function renderCatalog(){const g=$('#catalog');if(!g)return;const rows=visible();g.innerHTML=rows.length?rows.map(p=>card(p)).join(''):`<p class="empty-state">${locale==='ar'?'لا توجد نتائج مطابقة.':'No matching solutions.'}</p>`;bindCards()}
function renderFeatured(){const g=$('#featured-catalog');if(!g)return;const rows=catalog.filter(p=>p.featured).slice(0,4);g.innerHTML=(rows.length?rows:catalog.slice(0,4)).map(p=>card(p,true)).join('');bindCards()}
function renderFilters(){const f=$('#filters');if(!f)return;const cats=[['all',copy.all],...categories.map(c=>[c.slug,locale==='ar'?c.name_ar:c.name_en])];f.innerHTML=`<label class="search-box"><span>⌕</span><input data-search aria-label="${copy.search}" placeholder="${copy.search}"></label>`+cats.map(([id,n],i)=>`<button class="filter ${i===0?'active':''}" data-filter="${esc(id)}">${esc(n)}</button>`).join('');$('[data-search]')?.addEventListener('input',e=>{query=e.target.value||'';renderCatalog()});$$('[data-filter]').forEach(b=>b.onclick=()=>{activeCategory=b.dataset.filter;$$('[data-filter]').forEach(x=>x.classList.toggle('active',x===b));renderCatalog()})}
function renderCart(){const count=cart.reduce((s,x)=>s+x.qty,0);$$('.cart-count').forEach(x=>x.textContent=count);const body=$('#cart-body'),totals=$('#cart-totals');if(!body)return;if(!count){body.innerHTML=`<p>${copy.empty}</p>`;if(totals)totals.innerHTML='';return}body.innerHTML=cart.map(x=>{const p=product(x.id);if(!p)return'';const t=translated(p),v=variant(x.variantId),vn=v?(locale==='ar'?v.name_ar:v.name_en):'';return `<div class="cart-row"><div><b>${esc(t.name)}${vn?' — '+esc(vn):''}</b><small>${money(unitPrice(x))}</small><div class="qty"><button data-minus="${esc(p.id)}" data-variant="${esc(x.variantId||'')}">−</button><span>${x.qty}</span><button data-plus="${esc(p.id)}" data-variant="${esc(x.variantId||'')}">+</button><button data-remove="${esc(p.id)}" data-variant="${esc(x.variantId||'')}">×</button></div></div><b>${money(unitPrice(x)*x.qty)}</b></div>`}).join('');const subtotal=cart.reduce((s,x)=>s+unitPrice(x)*x.qty,0),vat=Math.round(subtotal*Number(settings.vat_rate||0)*100)/100,total=subtotal+vat;if(totals)totals.innerHTML=`<div class="total-line"><span>${copy.subtotal}</span><b>${money(subtotal)}</b></div><div class="total-line"><span>${copy.vat}</span><b>${money(vat)}</b></div><div class="total-line final"><span>${copy.total}</span><b>${money(total)}</b></div><a class="primary" href="checkout.html">${copy.checkout} →</a>`;$$('[data-plus]').forEach(b=>b.onclick=()=>{const x=cart.find(i=>i.id===b.dataset.plus&&(i.variantId||'')===b.dataset.variant);if(x)setQty(x.id,x.variantId,x.qty+1)});$$('[data-minus]').forEach(b=>b.onclick=()=>{const x=cart.find(i=>i.id===b.dataset.minus&&(i.variantId||'')===b.dataset.variant);if(x)setQty(x.id,x.variantId,x.qty-1)});$$('[data-remove]').forEach(b=>b.onclick=()=>setQty(b.dataset.remove,b.dataset.variant||null,0))}
function openCart(){$('#cart-drawer')?.classList.add('open')}function closeCart(){$('#cart-drawer')?.classList.remove('open')}
function mapRemote(p){return{id:p.slug,remoteId:p.id,type:p.type,category:p.commerce_categories?.slug||'uncategorized',price:Number(p.price),featured:!!p.featured,en:{name:p.name_en||p.slug,eyebrow:p.eyebrow_en||'A SOLUTION',desc:p.description_en||'',bullets:Array.isArray(p.features_en)?p.features_en:[]},ar:{name:p.name_ar||p.name_en||p.slug,eyebrow:p.eyebrow_ar||p.eyebrow_en||'A SOLUTION',desc:p.description_ar||p.description_en||'',bullets:Array.isArray(p.features_ar)?p.features_ar:[]}}}
async function hydrate(){try{const [rows,cats,s]=await Promise.all([ASolutionRemote.listProducts(),ASolutionRemote.listCategories(),ASolutionRemote.listSettings()]);if(rows?.length)catalog=rows.map(mapRemote);categories=cats||[];settings=s||settings;const physical=(rows||[]).filter(p=>p.type==='physical');variants=(await Promise.all(physical.map(p=>ASolutionRemote.listVariants(p.id).catch(()=>[])))).flat();normalize();renderFilters();renderFeatured();renderCatalog();renderCart()}catch(e){console.info('Using storefront fallback',e);renderFilters();renderFeatured();renderCatalog();renderCart()}}
function boot(){renderFilters();renderFeatured();renderCatalog();renderCart();$$('.wishlist-count').forEach(x=>x.textContent=wishlist.length);$$('[data-cart-open]').forEach(b=>b.onclick=openCart);$$('[data-cart-close]').forEach(b=>b.onclick=closeCart);hydrate()}
if(document.readyState==='loading')addEventListener('DOMContentLoaded',boot,{once:true});else boot();
window.ASolutionStorefront={visualForProduct,renderFeatured,renderCatalog,openCart};
})();