(function(){
'use strict';
const locale=document.documentElement.lang==='ar'?'ar':'en',KEY='asolution_cart_v2';let cart=[];try{cart=JSON.parse(localStorage.getItem(KEY)||'[]')}catch{cart=[]}let products=[],variants=[],settings=null;
const labels=locale==='ar'?{empty:'السلة فارغة',subtotal:'المجموع',vat:'الضريبة',shipping:'الشحن',total:'الإجمالي',discount:'الخصم',invalid:'راجع البيانات المطلوبة.',success:'تم إنشاء طلبك بنجاح.',ref:'رقم الطلب',sending:'جاري إنشاء الطلب...',offline:'تعذر الاتصال بالخادم.',cod:'الدفع عند الاستلام',bank:'تحويل بنكي',invoice:'فاتورة / دفع يدوي',online:'دفع إلكتروني'}:{empty:'Your cart is empty.',subtotal:'Subtotal',vat:'VAT',shipping:'Shipping',total:'Total',discount:'Discount',invalid:'Please review the required details.',success:'Your order has been created.',ref:'Order reference',sending:'Creating your order...',offline:'Could not reach the server.',cod:'Cash on delivery',bank:'Bank transfer',invoice:'Invoice / manual',online:'Online payment'};
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function productBySlug(slug){return products.find(p=>p.slug===slug)}function variantById(id){return variants.find(v=>v.id===id)}function itemPrice(x){const p=productBySlug(x.id),v=x.variantId?variantById(x.variantId):null;return Number(v?.price??p?.price??0)}
function subtotal(){return cart.reduce((s,x)=>s+itemPrice(x)*Number(x.qty||0),0)}
function renderSummary(){const box=document.querySelector('#summary');if(!box)return;if(!cart.length){box.innerHTML=`<p>${labels.empty}</p>`;return}const sub=subtotal(),shipping=estimateShipping(sub),vat=Math.round((sub+shipping)*Number(settings?.vat_rate??.15)*100)/100,total=Math.round((sub+shipping+vat)*100)/100;box.innerHTML=cart.map(x=>{const p=productBySlug(x.id),v=variantById(x.variantId);const name=locale==='ar'?(p?.name_ar||p?.name_en):(p?.name_en||p?.slug);return `<div class="total-line"><span>${esc(name)}${v?' — '+esc(locale==='ar'?v.name_ar:v.name_en):''} × ${Number(x.qty)}</span><b>${money(itemPrice(x)*x.qty)}</b></div>`}).join('')+`<hr><div class="total-line"><span>${labels.subtotal}</span><b>${money(sub)}</b></div><div class="total-line"><span>${labels.shipping}</span><b>${money(shipping)}</b></div><div class="total-line"><span>${labels.vat}</span><b>${money(vat)}</b></div><div class="total-line final"><span>${labels.total}</span><b>${money(total)}</b></div>`;}
function money(v){return new Intl.NumberFormat(locale==='ar'?'ar-SA':'en-SA',{style:'currency',currency:settings?.currency||'SAR'}).format(Number(v)||0)}
function physicalItems(){return cart.filter(x=>productBySlug(x.id)?.type==='physical')}function estimateShipping(sub){if(!physicalItems().length)return 0;const method=document.querySelector('[name=shipping_method]')?.value;if(method==='pickup')return 0;const threshold=Number(settings?.free_shipping_threshold||0);if(threshold&&sub>=threshold)return 0;return Number(settings?.flat_shipping_rate||0)}
function renderOptions(){const payment=document.querySelector('[name=payment_method]'),shipping=document.querySelector('[name=shipping_method]');if(payment){const types=new Set(cart.map(x=>productBySlug(x.id)?.type)),methods=settings?.enabled_payment_methods||['invoice','bank_transfer'];payment.innerHTML=methods.filter(m=>m!=='cod'||(settings?.cod_enabled&&types.size===1&&types.has('physical'))).map(m=>`<option value="${esc(m)}">${esc(m==='cod'?labels.cod:m==='bank_transfer'?labels.bank:m==='invoice'?labels.invoice:labels.online)}</option>`).join('')}if(shipping){const hasPhysical=physicalItems().length>0;shipping.closest('.field').hidden=!hasPhysical;shipping.innerHTML=`<option value="shipping">${labels.shipping}</option>`+(settings?.pickup_enabled?'<option value="pickup">Pickup</option>':'');shipping.onchange=renderSummary}}
async function boot(){try{[products,settings]=await Promise.all([ASolutionRemote.listProducts(),ASolutionRemote.listSettings()]);const ids=cart.map(x=>x.variantId).filter(Boolean);if(ids.length){const groups=await Promise.all([...new Set(cart.map(x=>productBySlug(x.id)?.id).filter(Boolean))].map(id=>ASolutionRemote.listVariants(id)));variants=groups.flat()}renderOptions();renderSummary()}catch(e){document.querySelector('#checkout-status').textContent=labels.offline+' '+(e?.message||'')}}
document.querySelector('#checkout-form')?.addEventListener('submit',async e=>{e.preventDefault();const data=Object.fromEntries(new FormData(e.currentTarget)),status=document.querySelector('#checkout-status'),v=(window.ASolutionCommerceDomain||ASolutionStore).validateCheckout(data);if(!v.valid){status.textContent=labels.invalid;return}if(!cart.length){status.textContent=labels.empty;return}status.textContent=labels.sending;const payload={customer:data,items:cart.map(x=>({slug:x.id,quantity:x.qty,variant_id:x.variantId||null})),coupon_code:data.coupon_code||'',payment_method:data.payment_method||'invoice',shipping_method:data.shipping_method||null,locale,idempotency_key:crypto.randomUUID(),attribution:{source:new URLSearchParams(location.search).get('utm_source')||'',medium:new URLSearchParams(location.search).get('utm_medium')||'',campaign:new URLSearchParams(location.search).get('utm_campaign')||''}};try{const order=await ASolutionRemote.createOrder(payload);if(!['invoice','bank_transfer','cod'].includes(order.payment_method)){status.textContent='Redirecting to secure payment…';const pay=await ASolutionRemote.createPayment(order.order_number,order.public_token,order.payment_method);location.href=pay.checkout_url;return}localStorage.removeItem(KEY);cart=[];status.className='success';status.textContent=`${labels.success} ${labels.ref}: ${order.order_number} — ${money(order.total)}`;e.currentTarget.reset();renderSummary()}catch(err){status.className='error';status.textContent=labels.offline+' '+(err?.message||'')}});
boot();
})();
