(function(){'use strict';
const locale=document.documentElement.lang==='ar'?'ar':'en',KEY='asolution_cart_v2',id=new URLSearchParams(location.search).get('id'),root=document.querySelector('#product-root'),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));let product=null,variants=[];
const visuals={'web-launch':['photo-1460925895917-afdab827c52f','photo-1516321318423-f06f85e504b3','photo-1497366811353-6870744d04b2'],commerce:['photo-1556742049-0cfed4f6a45d','photo-1556742111-a301076d9d18','photo-1556742502-ec7c0e9f34b1'],'brand-system':['photo-1558655146-9f40138edfeb','photo-1561070791-2526d30994b5','photo-1542744173-8e7e53415bb0'],growth:['photo-1551288049-bebda4e38f71','photo-1460925895917-afdab827c52f','photo-1552664730-d307ca884978'],crm:['photo-1551434678-e076c223a692','photo-1556761175-b413da4baf72','photo-1522071820081-009f0129c71c'],social:['photo-1611162617474-5b21e879e113','photo-1611162616305-c69b3fa7fbe0','photo-1492724441997-5dc865305da7']};
const img=(pid,i=0)=>`https://images.unsplash.com/${(visuals[pid]||visuals['web-launch'])[i]}?auto=format&fit=crop&w=${i?1000:1700}&q=88`;
const c=locale==='ar'?{bad:'الحل غير موجود',from:'ابتداءً من',add:'أضف للسلة',includes:'ماذا ستحصل عليه',reviews:'آراء العملاء',back:'العودة للمتجر',variant:'الخيار'}:{bad:'Solution not found',from:'FROM',add:'ADD TO CART',includes:"WHAT YOU’LL GET",reviews:'CLIENT REVIEWS',back:'BACK TO STORE',variant:'OPTION'};
function read(){try{const v=JSON.parse(localStorage.getItem(KEY)||'[]');return Array.isArray(v)?v:[]}catch{return[]}}function save(v){try{localStorage.setItem(KEY,JSON.stringify(v))}catch{}}
const money=v=>new Intl.NumberFormat(locale==='ar'?'ar-SA':'en-SA',{style:'currency',currency:'SAR'}).format(Number(v)||0);
function add(){const variantId=document.querySelector('#variant-select')?.value||null,cart=read(),item=cart.find(x=>x.id===id&&(x.variantId||null)===(variantId||null));if(item)item.qty=Math.min(99,Number(item.qty||0)+1);else cart.push({id,qty:1,variantId});save(cart);location.href='index.html'}
function setMeta(t){document.title=`${t.name} — A Solution Store`;let m=document.querySelector('meta[name=description]');if(!m){m=document.createElement('meta');m.name='description';document.head.appendChild(m)}m.content=(t.desc||'').slice(0,160);let canonical=document.querySelector('link[rel=canonical]');if(!canonical){canonical=document.createElement('link');canonical.rel='canonical';document.head.appendChild(canonical)}canonical.href=location.href.split('#')[0]}
function render(){if(!root)return;if(!product){root.innerHTML=`<section class="product-copy"><h1>${c.bad}</h1><a class="primary" href="index.html">${c.back} ↗</a></section>`;return}const t=product[locale],variantMarkup=variants.length?`<label class="field product-variant"><span>${c.variant}</span><select id="variant-select">${variants.map(v=>`<option value="${esc(v.id)}">${esc(locale==='ar'?(v.name_ar||v.name_en):(v.name_en||v.name_ar))} — ${money(v.price??product.price)}${v.inventory_qty!=null?' · '+v.inventory_qty+' in stock':''}</option>`).join('')}</select></label>`:'';root.classList.add('product-experience');root.innerHTML=`<section class="product-visual-hero"><div class="product-art premium-product-art"><img class="product-art-img" src="${img(product.id)}" alt="${esc(t.name)}"></div><div class="product-copy premium-product-copy"><small>${esc(t.eyebrow||'A SOLUTION')}</small><h1>${esc(t.name)}</h1><p class="product-lead">${esc(t.desc||'')}</p>${variantMarkup}<div class="price product-price">${c.from} ${money(product.price)}</div><button class="primary product-add" id="product-add">${c.add} +</button></div></section><section class="product-story"><span class="section-no">THE OUTCOME / VISUAL PREVIEW</span><div class="product-gallery"><img src="${img(product.id,0)}" alt=""><img src="${img(product.id,1)}" alt=""><img src="${img(product.id,2)}" alt=""></div><div class="product-deliverables"><h2>${c.includes}</h2><ul>${(t.bullets||[]).map(x=>`<li>${esc(x)}</li>`).join('')}</ul></div><div class="delivery-steps"><article><b>01</b><h4>ALIGN</h4><p>We lock the business objective, scope and inputs.</p></article><article><b>02</b><h4>CREATE</h4><p>Strategy, design and implementation move as one.</p></article><article><b>03</b><h4>DELIVER</h4><p>You receive a polished, launch-ready business solution.</p></article></div><div id="product-reviews" class="reviews-block"><h3>${c.reviews}</h3></div></section>`;document.querySelector('#product-add').onclick=add;setMeta(t);loadReviews()}
async function loadReviews(){const box=document.querySelector('#product-reviews');try{const reviews=await ASolutionRemote.listReviews(product.remoteId);box.innerHTML+=reviews?.length?reviews.map(r=>`<article class="review"><b>${'★'.repeat(r.rating)}${'☆'.repeat(5-r.rating)}</b><h4>${esc(r.title||'')}</h4><p>${esc(r.body||'')}</p></article>`).join(''):`<p>${locale==='ar'?'لا توجد تقييمات منشورة بعد.':'No published reviews yet.'}</p>`}catch{}}
(async()=>{try{const rows=await ASolutionRemote.listProducts(),r=rows.find(x=>x.slug===id);if(!r){render();return}product={id:r.slug,remoteId:r.id,type:r.type,price:Number(r.price),en:{name:r.name_en,eyebrow:r.eyebrow_en||'A SOLUTION',desc:r.description_en||'',bullets:Array.isArray(r.features_en)?r.features_en:[]},ar:{name:r.name_ar||r.name_en,eyebrow:r.eyebrow_ar||r.eyebrow_en||'A SOLUTION',desc:r.description_ar||r.description_en||'',bullets:Array.isArray(r.features_ar)?r.features_ar:[]}};if(r.type==='physical')variants=await ASolutionRemote.listVariants(r.id);render()}catch(e){render()}})();
})();