(function(){
'use strict';
const cfg=window.ASOLUTION_STORE_CONFIG||{},sb=cfg.supabase||{},base=(sb.url||'').replace(/\/$/,'');const key=sb.publishableKey||'',SESSION='asolution_supabase_session';let runtimeProducts=[];
function session(){try{return JSON.parse(localStorage.getItem(SESSION)||'null')}catch{return null}}
function headers(auth=true){const s=session(),h={'Content-Type':'application/json','apikey':key};if(auth&&s?.access_token)h.Authorization='Bearer '+s.access_token;else if(key)h.Authorization='Bearer '+key;return h;}
async function request(url,opts={}){const r=await fetch(url,{...opts,headers:{...headers(opts.auth!==false),...(opts.headers||{})}});const text=await r.text();let data=null;try{data=text?JSON.parse(text):null}catch{data=text}if(!r.ok)throw new Error(data?.msg||data?.message||data?.error_description||data?.error||('HTTP '+r.status));return data;}
async function listSettings(){const rows=await request(base+'/rest/v1/commerce_settings?singleton=eq.true&select=*',{auth:false});return rows?.[0]||null;}
async function listCategories(){return request(base+'/rest/v1/commerce_categories?active=eq.true&select=*&order=sort_order.asc',{auth:false});}
async function listProducts(){runtimeProducts=await request(base+'/rest/v1/commerce_products?active=eq.true&status=eq.active&select=*,commerce_categories(slug,name_en,name_ar)&order=featured.desc,created_at.asc',{auth:false});return runtimeProducts;}
async function listVariants(productId){return request(base+'/rest/v1/commerce_product_variants?active=eq.true&product_id=eq.'+encodeURIComponent(productId)+'&select=*&order=name_en.asc',{auth:false});}
async function listReviews(productId){return request(base+'/rest/v1/commerce_reviews?status=eq.approved&product_id=eq.'+encodeURIComponent(productId)+'&select=rating,title,body,created_at&order=created_at.desc',{auth:false});}
async function signup(email,password,meta={}){const data=await request(base+'/auth/v1/signup',{method:'POST',body:JSON.stringify({email,password,data:meta}),auth:false});if(data?.access_token)localStorage.setItem(SESSION,JSON.stringify(data));return data;}
async function login(email,password){const data=await request(base+'/auth/v1/token?grant_type=password',{method:'POST',body:JSON.stringify({email,password}),auth:false});localStorage.setItem(SESSION,JSON.stringify(data));return data;}
async function logout(){try{await request(base+'/auth/v1/logout',{method:'POST'})}finally{localStorage.removeItem(SESSION)}}
async function me(){if(!session()?.access_token)return null;return request(base+'/auth/v1/user');}
async function myCustomer(){const u=await me();if(!u)return null;let rows=await request(base+'/rest/v1/commerce_customers?auth_user_id=eq.'+encodeURIComponent(u.id)+'&select=*');if(rows?.[0])return rows[0];const created=await request(base+'/rest/v1/commerce_customers',{method:'POST',headers:{Prefer:'return=representation'},body:JSON.stringify({auth_user_id:u.id,email:u.email,name:u.user_metadata?.name||u.email,locale:document.documentElement.lang==='ar'?'ar':'en',source:'account'})});return created?.[0]||null;}
async function myOrders(){const c=await myCustomer();if(!c)return[];return request(base+'/rest/v1/commerce_orders?customer_id=eq.'+c.id+'&select=*&order=created_at.desc');}
async function myAddresses(){const c=await myCustomer();if(!c)return[];return request(base+'/rest/v1/commerce_addresses?customer_id=eq.'+c.id+'&select=*&order=is_default.desc');}
async function addAddress(row){const c=await myCustomer();if(!c)throw new Error('LOGIN_REQUIRED');return request(base+'/rest/v1/commerce_addresses',{method:'POST',headers:{Prefer:'return=representation'},body:JSON.stringify({...row,customer_id:c.id})});}
async function deleteAddress(id){return request(base+'/rest/v1/commerce_addresses?id=eq.'+encodeURIComponent(id),{method:'DELETE'});}
async function myEntitlements(){const c=await myCustomer();if(!c)return[];return request(base+'/rest/v1/commerce_digital_entitlements?customer_id=eq.'+c.id+'&select=*,commerce_products(name_en,name_ar)&order=created_at.desc');}
async function entitlementFiles(productId){return request(base+'/rest/v1/commerce_digital_files?product_id=eq.'+encodeURIComponent(productId)+'&active=eq.true&select=id,label,version&order=created_at.asc');}
async function myServiceJobs(){const c=await myCustomer();if(!c)return[];return request(base+'/rest/v1/commerce_service_jobs?customer_id=eq.'+c.id+'&select=*,commerce_products(name_en,name_ar)&order=created_at.desc');}
async function requestReturn(orderId,reason){const c=await myCustomer();if(!c)throw new Error('LOGIN_REQUIRED');return request(base+'/rest/v1/commerce_returns',{method:'POST',headers:{Prefer:'return=representation'},body:JSON.stringify({order_id:orderId,customer_id:c.id,reason,status:'requested'})});}
async function myWishlist(){const c=await myCustomer();if(!c)return[];return request(base+'/rest/v1/commerce_wishlists?customer_id=eq.'+c.id+'&select=product_id,commerce_products(*)');}
async function addWishlist(productId){const c=await myCustomer();if(!c)throw new Error('LOGIN_REQUIRED');return request(base+'/rest/v1/commerce_wishlists',{method:'POST',headers:{Prefer:'resolution=merge-duplicates,return=representation'},body:JSON.stringify({customer_id:c.id,product_id:productId})});}
async function removeWishlist(productId){const c=await myCustomer();if(!c)throw new Error('LOGIN_REQUIRED');return request(base+'/rest/v1/commerce_wishlists?customer_id=eq.'+c.id+'&product_id=eq.'+productId,{method:'DELETE'});}
async function submitReview(productId,rating,title,body){const c=await myCustomer();if(!c)throw new Error('LOGIN_REQUIRED');return request(base+'/rest/v1/commerce_reviews',{method:'POST',body:JSON.stringify({product_id:productId,customer_id:c.id,rating:Number(rating),title,body})});}
async function createOrder(payload){const idempotency=payload.idempotency_key||crypto.randomUUID();return request(base+'/functions/v1/commerce-create-order',{method:'POST',headers:{'x-idempotency-key':idempotency},body:JSON.stringify({...payload,idempotency_key:idempotency})});}
async function createPayment(orderNumber,publicToken,paymentMethod){return request(base+'/functions/v1/commerce-create-payment',{method:'POST',body:JSON.stringify({order_number:orderNumber,public_token:publicToken,payment_method:paymentMethod}),auth:false});}
async function trackOrder(orderNumber,email,publicToken){return request(base+'/functions/v1/commerce-track-order',{method:'POST',body:JSON.stringify({order_number:orderNumber,email,public_token:publicToken}),auth:false});}
async function digitalDownload(entitlementId,fileId){return request(base+'/functions/v1/commerce-digital-download',{method:'POST',body:JSON.stringify({entitlement_id:entitlementId,file_id:fileId})});}
async function adminList(table,select='*',suffix=''){return request(base+'/rest/v1/'+table+'?select='+encodeURIComponent(select)+suffix);}
async function adminPatch(table,id,patch){return request(base+'/rest/v1/'+table+'?id=eq.'+encodeURIComponent(id),{method:'PATCH',headers:{Prefer:'return=representation'},body:JSON.stringify(patch)});}
async function adminInsert(table,row){return request(base+'/rest/v1/'+table,{method:'POST',headers:{Prefer:'return=representation'},body:JSON.stringify(row)});}
async function adminDelete(table,id){return request(base+'/rest/v1/'+table+'?id=eq.'+encodeURIComponent(id),{method:'DELETE'});}
function runtimeCatalog(){return runtimeProducts.map(p=>({id:p.slug,remoteId:p.id,type:p.type,price:Number(p.price),category:p.commerce_categories?.slug||'uncategorized'}));}
function runtimeNormalize(cart){const ids=new Set(runtimeCatalog().map(p=>p.id));return Array.isArray(cart)?cart.filter(x=>x&&ids.has(String(x.id))&&Number(x.qty)>0).map(x=>({id:String(x.id),qty:Math.min(99,Math.max(1,Math.floor(Number(x.qty)||1))),variantId:x.variantId?String(x.variantId):null})):[];}
const legacy=window.ASolutionStore;if(legacy){const oldAdd=legacy.addToCart,oldSet=legacy.setCartQty,oldRemove=legacy.removeFromCart;legacy.addToCart=function(cart,id,qty=1,variantId=null){const sid=String(id),available=runtimeCatalog().some(p=>p.id===sid);if(!available)return oldAdd(cart,id,qty);const next=runtimeNormalize(cart),key=variantId?String(variantId):null,item=next.find(x=>x.id===sid&&x.variantId===key),q=Math.min(99,Math.max(1,Math.floor(Number(qty)||1)));if(item)item.qty=Math.min(99,item.qty+q);else next.push({id:sid,qty:q,variantId:key});return next};legacy.setCartQty=function(cart,id,qty,variantId=null){const sid=String(id),key=variantId?String(variantId):null;if(!runtimeCatalog().some(p=>p.id===sid))return oldSet(cart,id,qty);if(Number(qty)<=0)return runtimeNormalize(cart).filter(x=>!(x.id===sid&&x.variantId===key));return runtimeNormalize(cart).map(x=>x.id===sid&&x.variantId===key?{...x,qty:Math.min(99,Math.max(1,Math.floor(Number(qty)||1)))}:x)};legacy.removeFromCart=function(cart,id,variantId=null){const sid=String(id),key=variantId?String(variantId):null;if(!runtimeCatalog().some(p=>p.id===sid))return oldRemove(cart,id);return runtimeNormalize(cart).filter(x=>!(x.id===sid&&x.variantId===key))};}
window.ASolutionRemote={session,request,listSettings,listCategories,listProducts,listVariants,listReviews,signup,login,logout,me,myCustomer,myOrders,myAddresses,addAddress,deleteAddress,myEntitlements,entitlementFiles,myServiceJobs,requestReturn,myWishlist,addWishlist,removeWishlist,submitReview,createOrder,createPayment,trackOrder,digitalDownload,adminList,adminPatch,adminInsert,adminDelete,runtimeCatalog};
(async()=>{try{const s=await listSettings();if(!s)return;const root=document.documentElement;if(s.accent)root.style.setProperty('--coral',s.accent);if(s.paper)root.style.setProperty('--paper',s.paper);if(s.ink)root.style.setProperty('--ink',s.ink);document.querySelectorAll('[data-store-name]').forEach(el=>el.textContent=document.documentElement.lang==='ar'?(s.store_name_ar||s.store_name):(s.store_name||'A Solution'));if(s.favicon_url){let link=document.querySelector('link[rel=icon]');if(!link){link=document.createElement('link');link.rel='icon';document.head.appendChild(link)}link.href=s.favicon_url}}catch(e){console.info('White-label settings fallback active')}})();
})();
