(function(){
'use strict';
const core=window.ASolutionStore||{},$=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)],locale=document.documentElement.lang==='ar'?'ar':'en',KEY='asolution_cart_v2',WKEY='asolution_wishlist_local';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function readArray(key){try{const v=JSON.parse(localStorage.getItem(key)||'[]');return Array.isArray(v)?v:[]}catch{return []}}function saveArray(key,v){try{localStorage.setItem(key,JSON.stringify(v))}catch{}}
let rawCart=readArray(KEY).filter(x=>x&&x.id&&Number(x.qty)>0).map(x=>({id:String(x.id),qty:Math.min(99,Math.max(1,Math.floor(Number(x.qty)||1))),variantId:x.variantId?String(x.variantId):null})),cart=[...rawCart],wishlist=readArray(WKEY).filter(x=>typeof x==='string'),catalog=(core.PRODUCTS||[]).map(p=>({...p,remoteId:null})),variants=[],categories=[],activeCategory='all',query='',settings={currency:'SAR',vat_rate:.15};
const copy=locale==='ar'?{add:'أضف للسلة',from:'ابتداءً من',empty:'السلة فارغة.',checkout:'إتمام الطلب',subtotal:'المجموع',vat:'الضريبة',total:'الإجمالي',view:'عرض الحل',wish:'المفضلة',search:'ابحث عن حل...',featured:'حل مميز',all:'كل الحلول'}:{add:'ADD TO CART',from:'FROM',empty:'Your cart is empty.',checkout:'CHECKOUT',subtotal:'Subtotal',vat:'VAT',total:'Total',view:'VIEW SOLUTION',wish:'WISHLIST',search:'Search solutions...',featured:'FEATURED SOLUTION',all:'All Solutions'};
const visualMap={'web-launch':'web-launch.svg',commerce:'commerce.svg','brand-system':'brand-system.svg',growth:'growth.svg',crm:'crm.svg',social:'social.svg'};function visualForProduct(id){const file=visualMap[id]||'web-launch.svg';return locale==='ar'?`../../store/assets/visuals/${file}`:`assets/visuals/${file}`}
function translated(p){return p?.[locale]||p?.en||{name:'A Solution',eyebrow:'A SOLUTION',desc:''}}function money(v){return new Intl.NumberFormat(locale==='ar'?'ar-SA':'en-SA',{style:'currency',currency:settings.currency||'SAR',maximumFractionDigits:2}).format(Number(v)||0)}function product(id){return catalog.find(p=>p.id===id)}function variant(id){return variants.find(v=>String(v.id)===String(id))}function unitPrice(x){return Number(variant(x.variantId)?.price??product(x.id)?.price??0)}
function normalizeAgainstRuntime(){const ids=new Set(catalog.map(p=>p.id));cart=rawCart.filter(x=>ids.has(x.id));saveArray(KEY,cart)}
function add(id,variantId=null){const p=product(id);if(!p)return;const key=variantId?String(variantId):null,item=cart.find(x=>x.id===id&&x.variantId===key);if(item)item.qty=Math.min(99,item.qty+1);else cart.push({id,qty:1,variantId:key});rawCart=[...cart];saveArray(KEY,cart);renderCart();openCart()}
function setQty(id,variantId,qty){const key=variantId?String(variantId):null;if(qty<=0)cart=cart.filter(x=>!(x.id===id&&x.variantId===key));else cart=cart.map(x=>x.id===id&&x.variantId===key?{...x,qty:Math.min(99,Math.max(1,qty))}:x);rawCart=[...cart];saveArray(KEY,cart);renderCart()}
function productCard(p){const t=translated(p),liked=wishlist.includes(p.id);return `<article class="catalog-card" data-cat="${esc(p.category||'uncategorized')}"><div class="catalog-art"><img src="${visualForProduct(p.id)}" alt="${esc(t.name)} visual" loading="lazy"></div><div class="catalog-body"><small>${esc(t.eyebrow||'A SOLUTION')}</small><h3>${esc(t.name)}</h3><p>${esc(t.desc||'')}</p><div class="price">${copy.from} ${money(p.price)}</div><div class="catalog-actions"><a href="product.html?id=${encodeURIComponent(p.id)}">${copy.view} ↗</a><button data-add="${esc(p.id)}">${copy.add}</button><button class="wish-inline" data-wishlist="${esc(p.id)}" aria-label="${copy.wish}">${liked?'♥':'♡'}</button></div></div></article>`}
function featuredCard(p){const t=translated(p),liked=wishlist.includes(p.id);return `<article class="featured-card"><div class="featured-art"><img src="${visualForProduct(p.id)}" alt="${esc(t.name)} visual" loading="lazy"></div><div class="featured-copy"><small>${esc(t.eyebrow||copy.featured)}</small><h3>${esc(t.name)}</h3><p>${esc(t.desc||'')}</p><div class="featured-price">${copy.from} ${money(p.price)}</div><div class="featured-actions"><a href="product.html?id=${encodeURIComponent(p.id)}">${copy.view} ↗</a><button data-add="${esc(p.id)}">+</button><button data-wishlist="${esc(p.id)}" aria-label="${copy.wish}">${liked?'♥':'♡'}</button></div></div></article>`}
function visible(){const q=query.toLowerCase().trim();return catalog.filter(p=>(activeCategory==='all'||p.category===activeCategory)&&(!q||`${p.en?.name||''} ${p.ar?.name||''} ${p.en?.desc||''} ${p.ar?.desc||''}`.toLowerCase().includes(q)))}
function bindCards(){$$('[data-add]').forEach(b=>b.onclick=()=>add(b.dataset.add));$$('[data-wishlist]').forEach(b=>b.onclick=async()=>{const id=b.dataset.wishlist;wishlist=wishlist.includes(id)?wishlist.filter(x=>x!==id):[...wishlist,id];saveArray(WKEY,wishlist);renderCatalog();renderFeatured();$$('.wishlist-count').forEach(x=>x.textContent=wishlist.length);try{const p=product(id),token=ASolutionRemote.session()?.access_token;if(p?.remoteId&&token){if(wishlist.includes(id))await ASolutionRemote.addWishlist(p.remoteId);else await ASolutionRemote.removeWishlist(p.remoteId)}}catch{}})}
function renderCatalog(){const g=$('#catalog');if(!g)return;const rows=visible();g.innerHTML=rows.length?rows.map(productCard).join(''):`<p class="empty-state">${locale==='ar'?'لا توجد نتائج مطابقة.':'No matching solutions.'}</p>`;bindCards()}
function renderFeatured(){const g=$('#featured-catalog');if(!g)return;const rows=catalog.filter(p=>p.featured).slice(0,5);g.innerHTML=(rows.length?rows:catalog.slice(0,5)).map(featuredCard).join('');bindCards()}
function renderFilters(){const f=$('#filters');if(!f)return;const cats=[['all',copy.all],...categories.map(c=>[c.slug,locale==='ar'?c.name_ar:c.name_en])];f.innerHTML=`<label class="search-box"><span>⌕</span><input data-search aria-label="${copy.search}" placeholder="${copy.search}"></label>`+cats.map(([id,n],i)=>`<button class="filter ${i===0?'active':''}" data-filter="${esc(id)}">${esc(n)}</button>`).join('');$('[data-search]')?.addEventListener('input',e=>{query=e.target.value||'';renderCatalog()});$$('[data-filter]').forEach(b=>b.onclick=()=>{activeCategory=b.dataset.filter;$$('[data-filter]').forEach(x=>x.classList.toggle('active',x===b));renderCatalog()});$$('[data-category-link]').forEach(a=>a.onclick=()=>{activeCategory=a.dataset.categoryLink;setTimeout(()=>$('#catalog-section')?.scrollIntoView({behavior:'smooth'}),0);renderCatalog()})}
function renderCart(){const count=cart.reduce((s,x)=>s+x.qty,0);$$('.cart-count').forEach(x=>x.textContent=count);const body=$('#cart-body'),totals=$('#cart-totals');if(!body)return;if(!count){body.innerHTML=`<p>${copy.empty}</p>`;if(totals)totals.innerHTML='';return}body.innerHTML=cart.map(x=>{const p=product(x.id);if(!p)return '';const t=translated(p),v=variant(x.variantId);return `<div class="cart-row"><div><b>${esc(t.name)}${v?' — '+esc(locale==='ar'?v.name_ar:v.name_en):''}</b><small>${money(unitPrice(x))}</small><div class="qty"><button data-minus="${esc(p.id)}" data-variant="${esc(x.variantId||'')}">−</button><span>${x.qty}</span><button data-plus="${esc(p.id)}" data-variant="${esc(x.variantId||'')}">+</button><button data-remove="${esc(p.id)}" data-variant="${esc(x.variantId||'')}">×</button></div></div><b>${money(unitPrice(x)*x.qty)}</b></div>`}).join('');const subtotal=cart.reduce((s,x)=>s+unitPrice(x)*x.qty,0),vat=Math.round(subtotal*Number(settings.vat_rate||0)*100)/100,total=subtotal+vat;if(totals)totals.innerHTML=`<div class="total-line"><span>${copy.subtotal}</span><b>${money(subtotal)}</b></div><div class="total-line"><span>${copy.vat}</span><b>${money(vat)}</b></div><div class="total-line final"><span>${copy.total}</span><b>${money(total)}</b></div><a class="primary" href="checkout.html">${copy.checkout} →</a>`;$$('[data-plus]').forEach(b=>b.onclick=()=>{const x=cart.find(i=>i.id===b.dataset.plus&&(i.variantId||'')===b.dataset.variant);if(x)setQty(x.id,x.variantId,x.qty+1)});$$('[data-minus]').forEach(b=>b.onclick=()=>{const x=cart.find(i=>i.id===b.dataset.minus&&(i.variantId||'')===b.dataset.variant);if(x)setQty(x.id,x.variantId,x.qty-1)});$$('[data-remove]').forEach(b=>b.onclick=()=>setQty(b.dataset.remove,b.dataset.variant||null,0))}
function openCart(){$('#cart-drawer')?.classList.add('open')}function closeCart(){$('#cart-drawer')?.classList.remove('open')}
function mapRemote(p){return {id:p.slug,remoteId:p.id,type:p.type,category:p.commerce_categories?.slug||'uncategorized',price:Number(p.price),featured:!!p.featured,en:{name:p.name_en||p.slug,eyebrow:p.eyebrow_en||'A SOLUTION',desc:p.description_en||'',bullets:Array.isArray(p.features_en)?p.features_en:[]},ar:{name:p.name_ar||p.name_en||p.slug,eyebrow:p.eyebrow_ar||'A SOLUTION',desc:p.description_ar||p.description_en||'',bullets:Array.isArray(p.features_ar)?p.features_ar:[]}}}
async function hydrate(){try{const [rows,cats,s]=await Promise.all([ASolutionRemote.listProducts(),ASolutionRemote.listCategories(),ASolutionRemote.listSettings()]);if(rows?.length)catalog=rows.map(mapRemote);categories=cats||[];settings=s||settings;const groups=await Promise.all(rows.filter(p=>p.type==='physical').map(p=>ASolutionRemote.listVariants(p.id).catch(()=>[])));variants=groups.flat();normalizeAgainstRuntime();renderFilters();renderFeatured();renderCatalog();renderCart()}catch(e){console.info('Using storefront fallback',e);renderFilters();renderFeatured();renderCatalog();renderCart()}}
function boot(){renderFilters();renderFeatured();renderCatalog();renderCart();$$('.wishlist-count').forEach(x=>x.textContent=wishlist.length);$$('[data-cart-open]').forEach(b=>b.onclick=openCart);$$('[data-cart-close]').forEach(b=>b.onclick=closeCart);hydrate()}
if(document.readyState==='loading')addEventListener('DOMContentLoaded',boot,{once:true});else boot();window.ASolutionStorefront={visualForProduct,renderFeatured,renderCatalog,openCart};})();
