(function(){
'use strict';
const core=window.ASolutionStore||{};
const {PRODUCTS=[],CATEGORIES={en:[],ar:[]},getProduct,formatMoney,normalizeCart,addToCart,setCartQty,removeFromCart,calculateTotals}=core;
const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const locale=document.documentElement.lang==='ar'?'ar':'en';
const KEY='asolution_cart_v2', WKEY='asolution_wishlist_local', CKEY='asolution_coupon';
function safeReadArray(key){try{const value=JSON.parse(localStorage.getItem(key)||'[]');return Array.isArray(value)?value:[]}catch(e){return []}}
function safeGet(key,fallback=''){try{return localStorage.getItem(key)??fallback}catch(e){return fallback}}
function safeSet(key,value){try{localStorage.setItem(key,value)}catch(e){console.info('Local storage unavailable; continuing in memory')}}
let cart=typeof normalizeCart==='function'?normalizeCart(safeReadArray(KEY)):[];
let wishlist=safeReadArray(WKEY).filter(x=>typeof x==='string');
let activeCategory='all', query='', catalog=[...PRODUCTS];
const copy=locale==='ar'?{add:'أضف للسلة',from:'ابتداءً من',empty:'السلة فارغة.',checkout:'إتمام الطلب',subtotal:'المجموع',vat:'ضريبة 15%',total:'الإجمالي',view:'عرض الحل',wish:'المفضلة',search:'ابحث عن حل...',featured:'حل مميز'}:{add:'ADD TO CART',from:'FROM',empty:'Your cart is empty.',checkout:'CHECKOUT',subtotal:'Subtotal',vat:'VAT 15%',total:'Total',view:'VIEW SOLUTION',wish:'WISHLIST',search:'Search solutions...',featured:'FEATURED SOLUTION'};
const visualMap={
 'web-launch':'web-launch.svg',commerce:'commerce.svg','brand-system':'brand-system.svg',growth:'growth.svg',crm:'crm.svg',social:'social.svg'
};
function visualForProduct(id){const file=visualMap[id]||'web-launch.svg';return locale==='ar'?`../../store/assets/visuals/${file}`:`assets/visuals/${file}`}
function money(v){return typeof formatMoney==='function'?formatMoney(v,locale):`${Number(v)||0} SAR`}
function save(){safeSet(KEY,JSON.stringify(cart));renderCart()}
function saveWish(){safeSet(WKEY,JSON.stringify(wishlist));renderCatalog();renderFeatured();$$('.wishlist-count').forEach(x=>x.textContent=wishlist.length)}
function translated(p){return p?.[locale]||p?.en||{name:'A Solution',eyebrow:'A SOLUTION',desc:''}}
function productCard(p){const t=translated(p),liked=wishlist.includes(p.id);return `<article class="catalog-card" data-cat="${p.category||'digital'}"><div class="catalog-art"><img src="${visualForProduct(p.id)}" alt="${String(t.name).replace(/"/g,'&quot;')} visual"></div><div class="catalog-body"><small>${t.eyebrow||'A SOLUTION'}</small><h3>${t.name}</h3><p>${t.desc||''}</p><div class="price">${copy.from} ${money(p.price)}</div><div class="catalog-actions"><a href="product.html?id=${encodeURIComponent(p.id)}">${copy.view} ↗</a><button data-add="${p.id}">${copy.add}</button><button class="wish-inline" data-wishlist="${p.id}" aria-label="${copy.wish}">${liked?'♥':'♡'}</button></div></div></article>`}
function featuredCard(p){const t=translated(p),liked=wishlist.includes(p.id);return `<article class="featured-card"><div class="featured-art"><img src="${visualForProduct(p.id)}" alt="${String(t.name).replace(/"/g,'&quot;')} visual"></div><div class="featured-copy"><small>${t.eyebrow||copy.featured}</small><h3>${t.name}</h3><p>${t.desc||''}</p><div class="featured-price">${copy.from} ${money(p.price)}</div><div class="featured-actions"><a href="product.html?id=${encodeURIComponent(p.id)}">${copy.view} ↗</a><button data-add="${p.id}">+</button><button data-wishlist="${p.id}" aria-label="${copy.wish}">${liked?'♥':'♡'}</button></div></div></article>`}
function visibleProducts(){const q=query.toLowerCase().trim();return catalog.filter(p=>(activeCategory==='all'||p.category===activeCategory)&&(!q||`${p.en?.name||''} ${p.ar?.name||''} ${p.en?.desc||''} ${p.ar?.desc||''}`.toLowerCase().includes(q)))}
function bindCards(){
  $$('[data-add]').forEach(b=>b.onclick=()=>{if(typeof addToCart!=='function')return;cart=addToCart(cart,b.dataset.add);save();openCart()});
  $$('[data-wishlist]').forEach(b=>b.onclick=async()=>{const id=b.dataset.wishlist;wishlist=wishlist.includes(id)?wishlist.filter(x=>x!==id):[...wishlist,id];saveWish();try{const rows=await window.ASolutionRemote?.listProducts?.();const remote=rows?.find(x=>x.slug===id),token=window.ASolutionRemote?.session?.()?.access_token;if(remote&&token){if(wishlist.includes(id))await window.ASolutionRemote.addWishlist(remote.id);else await window.ASolutionRemote.removeWishlist(remote.id)}}catch(e){console.info('Remote wishlist sync skipped')}})
}
function renderCatalog(){const g=$('#catalog');if(!g)return;const rows=visibleProducts();g.innerHTML=rows.length?rows.map(productCard).join(''):`<p class="empty-state">${locale==='ar'?'لا توجد نتائج مطابقة.':'No matching solutions.'}</p>`;bindCards()}
function renderFeatured(){const g=$('#featured-catalog');if(!g)return;const preferred=['web-launch','commerce','crm','brand-system','growth'];const featured=preferred.map(id=>catalog.find(p=>p.id===id)).filter(Boolean);const rows=featured.length?featured:catalog.filter(p=>p.featured!==false).slice(0,5);g.innerHTML=rows.map(featuredCard).join('');bindCards()}
function setActiveCategory(category){activeCategory=category||'all';$$('[data-filter]').forEach(x=>x.classList.toggle('active',x.dataset.filter===activeCategory));renderCatalog()}
function renderFilters(){const f=$('#filters');if(!f)return;const cats=CATEGORIES[locale]||[];f.innerHTML=`<label class="search-box"><span>⌕</span><input data-search aria-label="${copy.search}" placeholder="${copy.search}"></label>`+cats.map(([id,n],i)=>`<button class="filter ${i===0?'active':''}" data-filter="${id}">${n}</button>`).join('');const input=$('[data-search]');if(input)input.oninput=e=>{query=e.target.value||'';renderCatalog()};$$('[data-filter]').forEach(b=>b.onclick=()=>setActiveCategory(b.dataset.filter));$$('[data-category-link]').forEach(a=>a.onclick=()=>{setActiveCategory(a.dataset.categoryLink);setTimeout(()=>$('#catalog-section')?.scrollIntoView({behavior:'smooth'}),0)})}
function renderCart(){const count=cart.reduce((s,x)=>s+(Number(x.qty)||0),0);$$('.cart-count').forEach(x=>x.textContent=count);const body=$('#cart-body'),totals=$('#cart-totals');if(!body)return;if(!count){body.innerHTML=`<p>${copy.empty}</p>`;if(totals)totals.innerHTML='';return}body.innerHTML=cart.map(x=>{const p=typeof getProduct==='function'?getProduct(x.id):catalog.find(y=>y.id===x.id);if(!p)return '';const t=translated(p);return `<div class="cart-row"><div><b>${t.name}</b><small>${money(p.price)}</small><div class="qty"><button data-minus="${p.id}">−</button><span>${x.qty}</span><button data-plus="${p.id}">+</button><button data-remove="${p.id}">×</button></div></div><b>${money(p.price*x.qty)}</b></div>`}).join('');const discount=Number(safeGet('asolution_discount_estimate','0')||0),t=typeof calculateTotals==='function'?calculateTotals(cart,{discount}):{subtotal:0,vat:0,total:0};if(totals)totals.innerHTML=`<div class="total-line"><span>${copy.subtotal}</span><b>${money(t.subtotal)}</b></div>${discount?`<div class="total-line"><span>${locale==='ar'?'الخصم':'Discount'}</span><b>− ${money(discount)}</b></div>`:''}<div class="total-line"><span>${copy.vat}</span><b>${money(t.vat)}</b></div><div class="total-line final"><span>${copy.total}</span><b>${money(t.total)}</b></div><a class="primary" href="checkout.html">${copy.checkout} →</a>`;$$('[data-plus]').forEach(b=>b.onclick=()=>{cart=addToCart(cart,b.dataset.plus);save()});$$('[data-minus]').forEach(b=>b.onclick=()=>{const x=cart.find(i=>i.id===b.dataset.minus);if(x)cart=setCartQty(cart,b.dataset.minus,x.qty-1);save()});$$('[data-remove]').forEach(b=>b.onclick=()=>{cart=removeFromCart(cart,b.dataset.remove);save()})}
function openCart(){const d=$('#cart-drawer');if(d)d.classList.add('open')}
function closeCart(){const d=$('#cart-drawer');if(d)d.classList.remove('open')}
function mapRemote(p){return {id:p.slug,remoteId:p.id,type:p.type,category:p.commerce_categories?.slug||'digital',price:Number(p.price),featured:p.featured,en:{name:p.name_en||p.slug,eyebrow:p.eyebrow_en||'A SOLUTION',desc:p.description_en||'',bullets:Array.isArray(p.features_en)?p.features_en:[]},ar:{name:p.name_ar||p.name_en||p.slug,eyebrow:p.eyebrow_ar||'A SOLUTION',desc:p.description_ar||p.description_en||'',bullets:Array.isArray(p.features_ar)?p.features_ar:[]}}}
async function hydrateCatalog(){try{const rows=await window.ASolutionRemote?.listProducts?.();if(rows?.length){catalog=rows.map(mapRemote);renderFeatured();renderCatalog()}}catch(e){console.info('Using local catalog fallback')}}
function bootStore(){renderFilters();renderFeatured();renderCatalog();try{renderCart()}catch(e){console.warn('Cart rendering skipped:',e)}$$('.wishlist-count').forEach(x=>x.textContent=wishlist.length);$$('[data-cart-open]').forEach(b=>b.onclick=openCart);$$('[data-cart-close]').forEach(b=>b.onclick=closeCart);hydrateCatalog()}
if(document.readyState==='loading')window.addEventListener('DOMContentLoaded',bootStore,{once:true});else bootStore();
window.ASolutionStorefront={visualForProduct,renderFeatured,renderCatalog,setActiveCategory};
})();
