import { createClient } from 'npm:@supabase/supabase-js@2';
const cors={'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'authorization, x-client-info, apikey, content-type, x-idempotency-key','Access-Control-Allow-Methods':'POST, OPTIONS'};
const json=(body:unknown,status=200)=>new Response(JSON.stringify(body),{status,headers:{...cors,'Content-Type':'application/json'}});
const money=(n:number)=>Math.round((Number(n)||0)*100)/100;
const clean=(v:unknown,max=500)=>String(v??'').trim().slice(0,max);
Deno.serve(async(req:Request)=>{
 if(req.method==='OPTIONS')return new Response('ok',{headers:cors});
 if(req.method!=='POST')return json({error:'Method not allowed'},405);
 try{
  const db=createClient(Deno.env.get('SUPABASE_URL')!,Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!,{auth:{persistSession:false}});
  const body=await req.json();const customer=body?.customer||{},items=Array.isArray(body?.items)?body.items:[];
  const email=clean(customer.email,254).toLowerCase(),name=clean(customer.name,160),phone=clean(customer.phone,64),city=clean(customer.city,120);
  if(!name||!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)||!phone||!city)return json({error:'Invalid customer data'},400);
  if(!items.length||items.length>50)return json({error:'Invalid cart'},400);
  const idempotencyKey=clean(req.headers.get('x-idempotency-key')||body?.idempotency_key,128)||crypto.randomUUID();
  const {data:prior}=await db.from('commerce_orders').select('order_number,total,payment_method,payment_status,public_token').eq('idempotency_key',idempotencyKey).maybeSingle();
  if(prior)return json({ok:true,replayed:true,...prior},200);
  const slugs=[...new Set(items.map((x:any)=>clean(x.slug,180)).filter(Boolean))];
  const {data:products,error:pe}=await db.from('commerce_products').select('id,slug,sku,type,name_en,price,inventory_qty,track_inventory,active,shipping_required,pickup_allowed,cod_allowed,download_limit,download_expiry_hours,service_requirements,low_stock_threshold').in('slug',slugs).eq('active',true).eq('status','active');if(pe)throw pe;
  const productMap=new Map((products||[]).map((p:any)=>[p.slug,p]));
  const variantIds=[...new Set(items.map((x:any)=>clean(x.variant_id,80)).filter(Boolean))];
  let variants:any[]=[];if(variantIds.length){const {data,error}=await db.from('commerce_product_variants').select('id,product_id,sku,name_en,price,inventory_qty,active').in('id',variantIds).eq('active',true);if(error)throw error;variants=data||[];}
  const variantMap=new Map(variants.map((v:any)=>[v.id,v]));let subtotal=0;const lines:any[]=[];let hasPhysical=false,hasNonPhysical=false;
  for(const raw of items){const p:any=productMap.get(clean(raw.slug,180));if(!p)return json({error:'Invalid product'},400);const q=Math.max(1,Math.min(99,Math.floor(Number(raw.quantity)||1)));let variant:any=null;if(raw.variant_id){variant=variantMap.get(clean(raw.variant_id,80));if(!variant||variant.product_id!==p.id)return json({error:'Invalid product variant'},400);}const available=variant?.inventory_qty??p.inventory_qty;if(p.track_inventory&&Number(available)<q)return json({error:`Insufficient inventory for ${p.name_en}`},409);const unit=money(variant?.price??p.price),line=money(unit*q);subtotal=money(subtotal+line);hasPhysical ||= p.type==='physical';hasNonPhysical ||= p.type!=='physical';lines.push({product_id:p.id,variant_id:variant?.id||null,product_type:p.type,name:variant?`${p.name_en} — ${variant.name_en}`:p.name_en,sku:variant?.sku||p.sku,unit_price:unit,quantity:q,line_total:line,metadata:{download_limit:p.download_limit,download_expiry_hours:p.download_expiry_hours,service_requirements:p.service_requirements}});}
  let discount=0,couponCode=clean(body?.coupon_code,80).toUpperCase();if(couponCode){const now=new Date().toISOString();const {data:c}=await db.from('commerce_coupons').select('*').eq('code',couponCode).eq('active',true).maybeSingle();if(!c||Number(c.minimum_subtotal||0)>subtotal||(c.starts_at&&c.starts_at>now)||(c.ends_at&&c.ends_at<now)||(c.max_uses&&c.uses>=c.max_uses))return json({error:'Coupon is not valid'},400);discount=money(c.kind==='percent'?subtotal*Math.min(100,Number(c.value))/100:Math.min(subtotal,Number(c.value)));}
  const {data:settings,error:se}=await db.from('commerce_settings').select('*').eq('singleton',true).single();if(se)throw se;const vatRate=Number(settings.vat_rate??.15),paymentMethod=clean(body?.payment_method,64)||'invoice';const enabled=new Set(settings.enabled_payment_methods||['invoice','bank_transfer']);if(!enabled.has(paymentMethod))return json({error:'Payment method is not enabled'},400);if(paymentMethod==='cod'&&(!settings.cod_enabled||hasNonPhysical||!hasPhysical))return json({error:'COD is not available for this cart'},400);
  let shipping=0,shippingMethod=clean(body?.shipping_method,64)||null;if(hasPhysical){if(shippingMethod==='pickup'){if(!settings.pickup_enabled)return json({error:'Pickup is not enabled'},400);}else{shipping=Number(settings.flat_shipping_rate||0);const threshold=Number(settings.free_shipping_threshold||0);if(threshold>0&&subtotal-discount>=threshold)shipping=0;shipping=money(shipping);}}
  const taxable=money(Math.max(0,subtotal-discount)+shipping),vat=money(taxable*vatRate),total=money(taxable+vat);
  let authUser:any=null;const auth=req.headers.get('authorization')||'';if(auth.startsWith('Bearer ')){const token=auth.slice(7);if(token.split('.').length===3){const {data}=await db.auth.getUser(token);authUser=data?.user||null;}}
  let commerceCustomer:any=(await db.from('commerce_customers').select('*').eq('email',email).maybeSingle()).data;const customerPayload={email,phone,name,company:clean(customer.company,160)||null,locale:clean(body?.locale,8)||'en',source:clean(body?.attribution?.source,120)||'store',auth_user_id:authUser?.id||commerceCustomer?.auth_user_id||null,updated_at:new Date().toISOString()};if(commerceCustomer){const {data,error}=await db.from('commerce_customers').update(customerPayload).eq('id',commerceCustomer.id).select().single();if(error)throw error;commerceCustomer=data;}else{const {data,error}=await db.from('commerce_customers').insert(customerPayload).select().single();if(error)throw error;commerceCustomer=data;}
  const orderNumber='AS-'+crypto.randomUUID().replaceAll('-','').slice(0,10).toUpperCase(),attribution=body?.attribution||{};
  const orderPayload={order_number:orderNumber,email,phone,name,company:clean(customer.company,160)||'',city,address_line:clean(customer.address_line,500)||'',currency:settings.currency||'SAR',subtotal,discount,vat,shipping,total,payment_method:paymentMethod,payment_status:paymentMethod==='cod'?'pending':'unpaid',shipping_method:shippingMethod||'',idempotency_key:idempotencyKey,source:clean(attribution.source,120)||'',medium:clean(attribution.medium,120)||'',campaign:clean(attribution.campaign,120)||'',notes:clean(customer.notes,3000)||'',locale:body?.locale||'en'};
  const {data:order,error:commitError}=await db.rpc('commerce_commit_order',{p_customer_id:commerceCustomer.id,p_order:orderPayload,p_items:lines,p_coupon_code:couponCode||null});if(commitError)throw commitError;
  return json({ok:true,order_number:orderNumber,public_token:order.public_token,total,subtotal,discount,shipping,vat,payment_method:paymentMethod,payment_status:order.payment_status},201);
 }catch(e){console.error(e);return json({error:'Unable to create order'},500);}
});
