create table if not exists public.site_content (
  id bigint generated by default as identity primary key,
  content_key text not null unique,
  value jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now(),
  updated_by uuid references auth.users(id)
);

alter table public.site_content enable row level security;

drop policy if exists "Public can read site content" on public.site_content;
create policy "Public can read site content"
on public.site_content for select
to anon, authenticated
using (true);

drop policy if exists "Admins can manage site content" on public.site_content;
create policy "Admins can manage site content"
on public.site_content for all
to authenticated
using (
  exists (
    select 1 from public.profiles p
    where p.id = auth.uid() and p.role = 'admin'
  )
)
with check (
  exists (
    select 1 from public.profiles p
    where p.id = auth.uid() and p.role = 'admin'
  )
);

alter table public.projects add column if not exists title_ar text;
alter table public.projects add column if not exists description_ar text;
alter table public.projects add column if not exists category text;
alter table public.projects add column if not exists category_ar text;
alter table public.projects add column if not exists sort_order integer not null default 0;

insert into public.site_content(content_key,value)
values
('home','{"en":{"hero":{"eyebrow":"CREATIVE × DIGITAL × TECHNOLOGY × BUSINESS","line1":"WE TURN","line2":"PROBLEMS INTO","line3":"MOMENTUM.","description":"One partner to shape the idea, build the experience, launch the campaign and move the business forward.","cta":"EXPLORE WHAT WE DO"}},"ar":{"hero":{"eyebrow":"إبداع × تسويق × تقنية × أعمال","line1":"نحوّل","line2":"التحديات إلى","line3":"حلول.","description":"شريك واحد يصوغ الفكرة، ويبني التجربة، ويطلق الحملة، ويحوّل التحديات إلى حلول تدفع أعمالك إلى الأمام.","cta":"اكتشف ما نقدمه"}}}'::jsonb),
('services','{"items":[]}'::jsonb),
('seo','{"en":{"title":"A Solution — Ideas that move business.","description":"A Solution is a Riyadh-based creative, digital, technology and business solutions studio."},"ar":{"title":"A Solution — حلول تحرّك أعمالك.","description":"A Solution شريك متكامل في الرياض للتسويق والإبداع والتقنية وحلول الأعمال والاستشارات والفعاليات."}}'::jsonb)
on conflict(content_key) do nothing;

update public.settings
set email='aalameenalsir@gmail.com'
where id=(select id from public.settings order by id limit 1);
