-- Recovered from remote migration history: 20260830180223
create table if not exists public.website_settings(
id bigint generated by default as identity primary key,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),
hero_kicker text not null default 'DIGITAL ADVERTISING & MEDIA SOLUTIONS',hero_title text not null default 'We make brands impossible to ignore.',
hero_description text not null default 'A Solution builds premium advertising experiences across screens, streets and digital platforms.',
primary_cta_label text not null default 'Start a project',primary_cta_link text not null default '#contact',
secondary_cta_label text not null default 'Explore our work',secondary_cta_link text not null default '#work',
about_title text not null default 'Built for attention. Designed for impact.',
about_text text not null default 'From strategy and creative to media placement and digital experiences, A Solution turns ideas into campaigns people notice and remember.',
services jsonb not null default '[]'::jsonb,metrics jsonb not null default '[]'::jsonb,hero_media_url text,
accent_color text not null default '#ff6b6b',background_color text not null default '#08090b',surface_color text not null default '#111318',text_color text not null default '#f5f5f0',motion_intensity text not null default 'high',
show_services boolean not null default true,show_projects boolean not null default true,show_about boolean not null default true,show_contact boolean not null default true);
alter table public.website_settings enable row level security;
